### ISSUE TITLE
bug: env vars are not set as uppercase

### ISSUE THREAD

**Issue by chrisjohnson00** [actions-tools/yaml-outputs#24]
Given a YAML file structured as such:

```
features:
  ghcr:
    enabled: true
```

Using the following `with` on the action:

```
        with:
          file-path: '.github/docker_build_settings.yaml'
          separator: '_'
          export-env-variables: true
```

The resulting env var is:
`features_ghcr_enabled=true`

General standard is for env vars to be upper case.
