### ISSUE TITLE
feature: Load and merge multiple yaml files

### ISSUE THREAD

**Issue by joernott** [actions-tools/yaml-outputs#25]
I am currently using this action to set a lot of variables for my testplans. We currently have a few situations where we have very similar yaml files. I would love to be able to implement something like
```
    - name: 'Load Testplans'
      uses: actions-tools/yaml-outputs@v2
      if: ${{ inputs.override != '' }}
      with:
        file-paths:
          - default.yaml
          - development.yaml
          - overrides.yaml
        separator: '_'
```
where it would first load "default.yaml" and merge "development.yaml" and afterwards "overrides.yaml". This would allow me to have a long default.yaml with all the default options (and even comments explaining them) and a relatively short "development.yaml" where I just change a few of them for my development runs. And "overrides.yaml" could be something, the developer puts in his feature branch which applies only then and there without touching "development.yaml"

Sadly, my typescript knowledge is not sufficient to send you a PR to implement this.
